_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 50
                - 51
                - 53
                - 55
                - 100
                - 103
                - 106
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 50
                - 51
                - 53
                - 55
                - 63
                - 100
                - 103
                - 106
            "3":
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.1
            "6": 4.47.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
